import { DeviceCategory, DeviceModel } from '@/lib/services/types';

// Apple device categories
export const appleCategories: DeviceCategory[] = [
  {
    id: 'macbook',
    name: 'MacBook',
    description: 'Apple MacBook laptops - Air and Pro models',
    icon: 'laptop',
    brands: ['Apple'],
    popularModels: ['MacBook Air M3', 'MacBook Pro 14" M4', 'MacBook Pro 16" M4'],
  },
  {
    id: 'imac',
    name: 'iMac',
    description: 'Apple iMac all-in-one desktop computers',
    icon: 'desktop',
    brands: ['Apple'],
    popularModels: ['iMac 24" M4', 'iMac 24" M3'],
  },
  {
    id: 'mac-mini',
    name: 'Mac Mini',
    description: 'Apple Mac Mini compact desktop computers',
    icon: 'cpu',
    brands: ['Apple'],
    popularModels: ['Mac Mini M4', 'Mac Mini M2'],
  },
  {
    id: 'mac-studio',
    name: 'Mac Studio',
    description: 'Apple Mac Studio high-performance compact desktops',
    icon: 'cpu',
    brands: ['Apple'],
    popularModels: ['Mac Studio M2 Ultra', 'Mac Studio M2 Max'],
  },
  {
    id: 'mac-pro',
    name: 'Mac Pro',
    description: 'Apple Mac Pro professional workstations',
    icon: 'cpu',
    brands: ['Apple'],
    popularModels: ['Mac Pro M2 Ultra', 'Mac Pro Intel'],
  },
  {
    id: 'iphone',
    name: 'iPhone',
    description: 'Apple iPhone smartphones',
    icon: 'smartphone',
    brands: ['Apple'],
    popularModels: ['iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16 Plus', 'iPhone 16', 'iPhone 15 Pro Max', 'iPhone 15 Pro'],
  },
  {
    id: 'ipad',
    name: 'iPad',
    description: 'Apple iPad tablets',
    icon: 'tablet',
    brands: ['Apple'],
    popularModels: ['iPad Pro 13" M4', 'iPad Pro 11" M4', 'iPad Air 13" M2', 'iPad Air 11" M2'],
  },
];

// MacBook models (2016-2025)
export const macbookModels: DeviceModel[] = [
  // MacBook Pro M4 (2024)
  {
    id: 'macbook-pro-14-m4-2024',
    categoryId: 'macbook',
    category: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 14" M4',
    year: 2024,
    imageUrl: '/images/devices/macbook-pro-14-m4-2024.jpg',
    specifications: {
      screen: { size: '14.2"', resolution: '3024x1964', type: 'Liquid Retina XDR' },
      processor: 'Apple M4, M4 Pro, or M4 Max (up to 14-core CPU, 32-core GPU)',
      memory: '16GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 5/4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 312.6, height: 221.2, depth: 15.5, weight: 1.55 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen flickering', 'Thermal management', 'Port connectivity', 'Battery optimization'],
    averageRepairCost: 450,
  },
  {
    id: 'macbook-pro-16-m4-2024',
    categoryId: 'macbook',
    category: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 16" M4',
    year: 2024,
    imageUrl: '/images/devices/macbook-pro-16-m4-2024.jpg',
    specifications: {
      screen: { size: '16.2"', resolution: '3456x2234', type: 'Liquid Retina XDR' },
      processor: 'Apple M4 Pro or M4 Max (up to 14-core CPU, 32-core GPU)',
      memory: '24GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 5/4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 355.7, height: 248.1, depth: 16.8, weight: 2.14 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen flickering', 'Thermal management', 'Port connectivity', 'Battery optimization'],
    averageRepairCost: 520,
  },

  // MacBook Air M3 (2024)
  {
    id: 'macbook-air-13-m3-2024',
    categoryId: 'macbook',
    category: 'macbook',
    brand: 'Apple',
    name: 'MacBook Air 13" M3',
    year: 2024,
    imageUrl: '/images/devices/macbook-air-13-m3-2024.jpg',
    specifications: {
      screen: { size: '13.6"', resolution: '2560x1664', type: 'Liquid Retina' },
      processor: 'Apple M3 (8-core CPU, 8/10-core GPU)',
      memory: '8GB - 24GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 304.1, height: 215, depth: 11.3, weight: 1.24 },
    },
    commonIssues: ['Battery drain', 'Keyboard issues', 'Screen flickering', 'Overheating'],
    averageRepairCost: 280,
  },
  {
    id: 'macbook-air-15-m3-2024',
    categoryId: 'macbook',
    category: 'macbook',
    brand: 'Apple',
    name: 'MacBook Air 15" M3',
    year: 2024,
    imageUrl: '/images/devices/macbook-air-15-m3-2024.jpg',
    specifications: {
      screen: { size: '15.3"', resolution: '2880x1864', type: 'Liquid Retina' },
      processor: 'Apple M3 (8-core CPU, 10-core GPU)',
      memory: '8GB - 24GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 340.4, height: 237.6, depth: 11.5, weight: 1.51 },
    },
    commonIssues: ['Battery drain', 'Keyboard issues', 'Screen flickering', 'Overheating'],
    averageRepairCost: 320,
  },

  // MacBook Pro M3 (2023)
  {
    id: 'macbook-pro-14-m3-2023',
    categoryId: 'macbook',
    category: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 14" M3',
    year: 2023,
    imageUrl: '/images/devices/macbook-pro-14-m3-2023.jpg',
    specifications: {
      screen: { size: '14.2"', resolution: '3024x1964', type: 'Liquid Retina XDR' },
      processor: 'Apple M3, M3 Pro, or M3 Max',
      memory: '8GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 312.6, height: 221.2, depth: 15.5, weight: 1.55 },
    },
    commonIssues: ['Screen flickering', 'Keyboard issues', 'Battery drain', 'Port problems'],
    averageRepairCost: 420,
  },

  // MacBook Air M1 (2020)
  {
    id: 'macbook-air-13-m1-2020',
    categoryId: 'macbook',
    category: 'macbook',
    brand: 'Apple',
    name: 'MacBook Air 13" M1',
    year: 2020,
    imageUrl: '/images/devices/macbook-air-13-m1-2020.jpg',
    specifications: {
      screen: { size: '13.3"', resolution: '2560x1600', type: 'Retina' },
      processor: 'Apple M1 (8-core CPU, 7/8-core GPU)',
      memory: '8GB - 16GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', '3.5mm headphone'],
      dimensions: { width: 304.1, height: 212.4, depth: 4.1, weight: 1.29 },
    },
    commonIssues: ['Screen coating wear', 'Keyboard issues', 'Battery drain', 'Port problems'],
    averageRepairCost: 280,
  },
];

// iPhone models (2016-2025)
export const iphoneModels: DeviceModel[] = [
  // iPhone 16 Series (2024)
  {
    id: 'iphone-16-pro-max',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 16 Pro Max',
    year: 2024,
    imageUrl: '/images/devices/iphone-16-pro-max.jpg',
    specifications: {
      screen: { size: '6.9"', resolution: '2868x1320', type: 'Super Retina XDR OLED ProMotion' },
      processor: 'A18 Pro',
      memory: '8GB',
      storage: '256GB - 1TB',
      cameras: 'Triple camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto 5x)',
      connectivity: 'USB-C, 5G, Wi-Fi 7, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Camera Control button problems'],
    averageRepairCost: 280,
  },
  {
    id: 'iphone-16-pro',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 16 Pro',
    year: 2024,
    imageUrl: '/images/devices/iphone-16-pro.jpg',
    specifications: {
      screen: { size: '6.3"', resolution: '2622x1206', type: 'Super Retina XDR OLED ProMotion' },
      processor: 'A18 Pro',
      memory: '8GB',
      storage: '128GB - 1TB',
      cameras: 'Triple camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto 5x)',
      connectivity: 'USB-C, 5G, Wi-Fi 7, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Camera Control button problems'],
    averageRepairCost: 260,
  },
  {
    id: 'iphone-16-plus',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 16 Plus',
    year: 2024,
    imageUrl: '/images/devices/iphone-16-plus.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A18',
      memory: '8GB',
      storage: '128GB - 512GB',
      cameras: 'Dual camera system (48MP Main, 12MP Ultra Wide)',
      connectivity: 'USB-C, 5G, Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Action button problems'],
    averageRepairCost: 220,
  },
  {
    id: 'iphone-16',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 16',
    year: 2024,
    imageUrl: '/images/devices/iphone-16.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A18',
      memory: '8GB',
      storage: '128GB - 512GB',
      cameras: 'Dual camera system (48MP Main, 12MP Ultra Wide)',
      connectivity: 'USB-C, 5G, Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Action button problems'],
    averageRepairCost: 200,
  },

  // iPhone 15 Series (2023)
  {
    id: 'iphone-15-pro-max',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 15 Pro Max',
    year: 2023,
    imageUrl: '/images/devices/iphone-15-pro-max.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A17 Pro',
      memory: '8GB',
      storage: '256GB - 1TB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 220,
  },
  {
    id: 'iphone-15-pro',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 15 Pro',
    year: 2023,
    imageUrl: '/images/devices/iphone-15-pro.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A17 Pro',
      memory: '8GB',
      storage: '128GB - 1TB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 200,
  },
  {
    id: 'iphone-15',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 15',
    year: 2023,
    imageUrl: '/images/devices/iphone-15.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A16 Bionic',
      memory: '6GB',
      storage: '128GB - 512GB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 160,
  },

  // iPhone 14 Series (2022)
  {
    id: 'iphone-14-pro-max',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 14 Pro Max',
    year: 2022,
    imageUrl: '/images/devices/iphone-14-pro-max.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A16 Bionic',
      memory: '6GB',
      storage: '128GB - 1TB',
    },
    commonIssues: ['Dynamic Island issues', 'Screen cracks', 'Battery degradation', 'Camera problems'],
    averageRepairCost: 200,
  },
  {
    id: 'iphone-12',
    categoryId: 'iphone',
    category: 'smartphone',
    brand: 'Apple',
    name: 'iPhone 12',
    year: 2020,
    imageUrl: '/images/devices/iphone-12.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2532x1170', type: 'Super Retina XDR OLED' },
      processor: 'A14 Bionic',
      memory: '4GB',
      storage: '64GB - 256GB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Charging issues', 'Speaker problems'],
    averageRepairCost: 140,
  },
];

// iMac models (2016-2025)
export const imacModels: DeviceModel[] = [
  {
    id: 'imac-24-m4-2024',
    categoryId: 'imac',
    category: 'desktop',
    brand: 'Apple',
    name: 'iMac 24" M4',
    year: 2024,
    imageUrl: '/images/devices/imac-24-m4-2024.jpg',
    specifications: {
      screen: { size: '24"', resolution: '4480x2520', type: '4.5K Retina' },
      processor: 'Apple M4 (8/10-core CPU, 8/10-core GPU)',
      memory: '16GB - 32GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['4x Thunderbolt 4', '2x USB 3', 'Gigabit Ethernet (optional)', '3.5mm headphone'],
      dimensions: { width: 547, height: 461.2, depth: 147, weight: 4.43 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Display uniformity', 'Thermal management', 'Port connectivity', 'Stand adjustment'],
    averageRepairCost: 420,
  },
];

// iPad models
export const ipadModels: DeviceModel[] = [
  {
    id: 'ipad-pro-13-m4-2024',
    categoryId: 'ipad',
    category: 'tablet',
    brand: 'Apple',
    name: 'iPad Pro 13" M4',
    year: 2024,
    imageUrl: '/images/devices/ipad-pro-13-m4-2024.jpg',
    specifications: {
      screen: { size: '13"', resolution: '2752x2064', type: 'Ultra Retina XDR OLED' },
      processor: 'Apple M4 (9/10-core CPU, 10-core GPU)',
      memory: '8GB - 16GB',
      storage: '256GB - 2TB',
      connectivity: 'USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
      cameras: '12MP Wide, 10MP Ultra Wide, LiDAR Scanner',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil Pro connectivity', 'USB-C port issues', 'OLED burn-in', 'Bent frame'],
    averageRepairCost: 350,
  },
  {
    id: 'ipad-air-11-m2-2024',
    categoryId: 'ipad',
    category: 'tablet',
    brand: 'Apple',
    name: 'iPad Air 11" M2',
    year: 2024,
    imageUrl: '/images/devices/ipad-air-11-m2-2024.jpg',
    specifications: {
      screen: { size: '11"', resolution: '2360x1640', type: 'Liquid Retina' },
      processor: 'Apple M2 (8-core CPU, 10-core GPU)',
      memory: '8GB',
      storage: '128GB - 1TB',
      connectivity: 'USB-C, Wi-Fi 6E, Bluetooth 5.3',
      cameras: '12MP Wide, 12MP Ultra Wide',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil connectivity', 'USB-C port issues', 'Touch ID problems', 'Speaker issues'],
    averageRepairCost: 250,
  },
];

// Combine all Apple devices
export const allAppleDevices: DeviceModel[] = [
  ...macbookModels,
  ...iphoneModels,
  ...imacModels,
  ...ipadModels,
];

export default {
  categories: appleCategories,
  devices: allAppleDevices,
  macbooks: macbookModels,
  iphones: iphoneModels,
  imacs: imacModels,
  ipads: ipadModels,
};