apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: production
    app: revivatech
  annotations:
    description: "Production namespace for RevivaTech platform"