import { DeviceCategory, DeviceModel } from '@/lib/services/types';

// Android device categories
export const androidCategories: DeviceCategory[] = [
  {
    id: 'android-phone',
    name: 'Android Phone',
    description: 'Android smartphones from all manufacturers',
    icon: 'smartphone',
    brands: ['Samsung', 'Google', 'OnePlus', 'Xiaomi', 'Huawei', 'Sony', 'Motorola'],
    popularModels: ['Samsung Galaxy S24', 'Google Pixel 8', 'OnePlus 12', 'Xiaomi 14'],
  },
  {
    id: 'android-tablet',
    name: 'Android Tablet',
    description: 'Android tablets and 2-in-1 devices',
    icon: 'tablet',
    brands: ['Samsung', 'Google', 'Lenovo', 'Huawei', 'Xiaomi'],
    popularModels: ['Samsung Galaxy Tab S9', 'Google Pixel Tablet', 'Lenovo Tab P11'],
  },
];

// Samsung Galaxy models
export const samsungModels: DeviceModel[] = [
  {
    id: 'samsung-galaxy-s24-ultra',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S24 Ultra',
    year: 2024,
    imageUrl: '/images/devices/samsung-galaxy-s24-ultra.jpg',
    specifications: {
      screen: { size: '6.8"', resolution: '3120x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 8 Gen 3',
      memory: '12GB - 16GB',
      storage: '256GB - 1TB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Reverse wireless charging'],
      dimensions: { width: 162.3, height: 79, depth: 8.6, weight: 232 },
    },
    commonIssues: ['Screen cracks', 'S Pen issues', 'Camera problems', 'Battery degradation'],
    averageRepairCost: 180,
  },
  {
    id: 'samsung-galaxy-s24-plus',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S24+',
    year: 2024,
    imageUrl: '/images/devices/samsung-galaxy-s24-plus.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '3120x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 8 Gen 3',
      memory: '12GB',
      storage: '256GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Reverse wireless charging'],
      dimensions: { width: 158.5, height: 75.9, depth: 7.7, weight: 196 },
    },
    commonIssues: ['Screen cracks', 'Camera problems', 'Battery degradation', 'Charging port issues'],
    averageRepairCost: 160,
  },
  {
    id: 'samsung-galaxy-s24',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S24',
    year: 2024,
    imageUrl: '/images/devices/samsung-galaxy-s24.jpg',
    specifications: {
      screen: { size: '6.2"', resolution: '2340x1080', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 8 Gen 3',
      memory: '8GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Reverse wireless charging'],
      dimensions: { width: 147, height: 70.6, depth: 7.6, weight: 167 },
    },
    commonIssues: ['Screen cracks', 'Camera problems', 'Battery degradation', 'Fingerprint sensor issues'],
    averageRepairCost: 140,
  },
  {
    id: 'samsung-galaxy-s23-ultra',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S23 Ultra',
    year: 2023,
    imageUrl: '/images/devices/samsung-galaxy-s23-ultra.jpg',
    specifications: {
      screen: { size: '6.8"', resolution: '3088x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 8 Gen 2',
      memory: '8GB - 12GB',
      storage: '256GB - 1TB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Reverse wireless charging'],
      dimensions: { width: 163.4, height: 78.1, depth: 8.9, weight: 234 },
    },
    commonIssues: ['Screen cracks', 'S Pen issues', 'Camera problems', 'Battery degradation'],
    averageRepairCost: 170,
  },
  {
    id: 'samsung-galaxy-tab-s9-ultra',
    categoryId: 'android-tablet',
    brand: 'Samsung',
    name: 'Galaxy Tab S9 Ultra',
    year: 2023,
    imageUrl: '/images/devices/samsung-galaxy-tab-s9-ultra.jpg',
    specifications: {
      screen: { size: '14.6"', resolution: '2960x1848', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 8 Gen 2',
      memory: '12GB - 16GB',
      storage: '256GB - 1TB',
      ports: ['USB-C 3.2', 'Wireless charging', 'S Pen support'],
      dimensions: { width: 326.4, height: 208.6, depth: 5.5, weight: 732 },
    },
    commonIssues: ['Screen cracks', 'S Pen connectivity', 'Keyboard dock issues', 'Charging problems'],
    averageRepairCost: 280,
  },
];

// Google Pixel models
export const pixelModels: DeviceModel[] = [
  {
    id: 'google-pixel-8-pro',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 8 Pro',
    year: 2023,
    imageUrl: '/images/devices/google-pixel-8-pro.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2992x1344', type: 'LTPO OLED' },
      processor: 'Google Tensor G3',
      memory: '12GB',
      storage: '128GB - 1TB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Reverse wireless charging'],
      dimensions: { width: 162.6, height: 76.5, depth: 8.8, weight: 213 },
    },
    commonIssues: ['Screen cracks', 'Camera bar issues', 'Battery degradation', 'Fingerprint sensor problems'],
    averageRepairCost: 160,
  },
  {
    id: 'google-pixel-8',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 8',
    year: 2023,
    imageUrl: '/images/devices/google-pixel-8.jpg',
    specifications: {
      screen: { size: '6.2"', resolution: '2400x1080', type: 'OLED' },
      processor: 'Google Tensor G3',
      memory: '8GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Reverse wireless charging'],
      dimensions: { width: 150.5, height: 70.8, depth: 8.9, weight: 187 },
    },
    commonIssues: ['Screen cracks', 'Camera bar issues', 'Battery degradation', 'Charging port problems'],
    averageRepairCost: 140,
  },
  {
    id: 'google-pixel-7a',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 7a',
    year: 2023,
    imageUrl: '/images/devices/google-pixel-7a.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2400x1080', type: 'OLED' },
      processor: 'Google Tensor G2',
      memory: '8GB',
      storage: '128GB',
      ports: ['USB-C 3.2', 'Wireless charging'],
      dimensions: { width: 152.4, height: 72.9, depth: 9, weight: 193.5 },
    },
    commonIssues: ['Screen cracks', 'Camera problems', 'Battery degradation', 'Overheating'],
    averageRepairCost: 120,
  },
  {
    id: 'google-pixel-tablet',
    categoryId: 'android-tablet',
    brand: 'Google',
    name: 'Pixel Tablet',
    year: 2023,
    imageUrl: '/images/devices/google-pixel-tablet.jpg',
    specifications: {
      screen: { size: '10.95"', resolution: '2560x1600', type: 'LCD' },
      processor: 'Google Tensor G2',
      memory: '8GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.2', 'Charging speaker dock'],
      dimensions: { width: 258, height: 169, depth: 8.1, weight: 493 },
    },
    commonIssues: ['Screen cracks', 'Dock connectivity', 'Speaker issues', 'Charging problems'],
    averageRepairCost: 180,
  },
];

// OnePlus models
export const oneplusModels: DeviceModel[] = [
  {
    id: 'oneplus-12',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 12',
    year: 2024,
    imageUrl: '/images/devices/oneplus-12.jpg',
    specifications: {
      screen: { size: '6.82"', resolution: '3168x1440', type: 'LTPO AMOLED' },
      processor: 'Snapdragon 8 Gen 3',
      memory: '12GB - 16GB',
      storage: '256GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Fast charging 100W'],
      dimensions: { width: 164.3, height: 75, depth: 9.15, weight: 220 },
    },
    commonIssues: ['Screen cracks', 'Camera issues', 'Battery degradation', 'Alert slider problems'],
    averageRepairCost: 150,
  },
  {
    id: 'oneplus-11',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 11',
    year: 2023,
    imageUrl: '/images/devices/oneplus-11.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '3216x1440', type: 'LTPO AMOLED' },
      processor: 'Snapdragon 8 Gen 2',
      memory: '8GB - 16GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Fast charging 100W'],
      dimensions: { width: 163.1, height: 74.1, depth: 8.53, weight: 205 },
    },
    commonIssues: ['Screen cracks', 'Camera issues', 'Battery degradation', 'Charging port problems'],
    averageRepairCost: 140,
  },
];

// Xiaomi models
export const xiaomiModels: DeviceModel[] = [
  {
    id: 'xiaomi-14-ultra',
    categoryId: 'android-phone',
    brand: 'Xiaomi',
    name: 'Xiaomi 14 Ultra',
    year: 2024,
    imageUrl: '/images/devices/xiaomi-14-ultra.jpg',
    specifications: {
      screen: { size: '6.73"', resolution: '3200x1440', type: 'LTPO AMOLED' },
      processor: 'Snapdragon 8 Gen 3',
      memory: '12GB - 16GB',
      storage: '256GB - 1TB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Fast charging 90W'],
      dimensions: { width: 161.4, height: 75.3, depth: 9.2, weight: 224 },
    },
    commonIssues: ['Screen cracks', 'Camera module issues', 'Battery degradation', 'MIUI software problems'],
    averageRepairCost: 160,
  },
  {
    id: 'xiaomi-13-pro',
    categoryId: 'android-phone',
    brand: 'Xiaomi',
    name: 'Xiaomi 13 Pro',
    year: 2023,
    imageUrl: '/images/devices/xiaomi-13-pro.jpg',
    specifications: {
      screen: { size: '6.73"', resolution: '3200x1440', type: 'LTPO AMOLED' },
      processor: 'Snapdragon 8 Gen 2',
      memory: '8GB - 12GB',
      storage: '256GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'Fast charging 120W'],
      dimensions: { width: 162.9, height: 74.6, depth: 8.38, weight: 210 },
    },
    commonIssues: ['Screen cracks', 'Camera issues', 'Battery degradation', 'Overheating'],
    averageRepairCost: 140,
  },
  {
    id: 'xiaomi-redmi-note-12',
    categoryId: 'android-phone',
    brand: 'Xiaomi',
    name: 'Redmi Note 12',
    year: 2023,
    imageUrl: '/images/devices/xiaomi-redmi-note-12.jpg',
    specifications: {
      screen: { size: '6.67"', resolution: '2400x1080', type: 'AMOLED' },
      processor: 'Snapdragon 685',
      memory: '4GB - 8GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 2.0', 'Wireless charging', '3.5mm headphone'],
      dimensions: { width: 165.9, height: 76.2, depth: 7.85, weight: 188 },
    },
    commonIssues: ['Screen cracks', 'Charging port issues', 'MIUI bugs', 'Camera problems'],
    averageRepairCost: 100,
  },
];

// Older Samsung Galaxy models (2016-2021)
export const samsungLegacyModels: DeviceModel[] = [
  {
    id: 'samsung-galaxy-s22-ultra',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S22 Ultra',
    year: 2022,
    imageUrl: '/images/devices/samsung-galaxy-s22-ultra.jpg',
    specifications: {
      screen: { size: '6.8"', resolution: '3088x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 8 Gen 1 / Exynos 2200',
      memory: '8GB - 12GB',
      storage: '128GB - 1TB',
      ports: ['USB-C 3.2', 'Wireless charging', 'S Pen support'],
      dimensions: { width: 163.3, height: 77.9, depth: 8.9, weight: 228 },
    },
    commonIssues: ['S Pen issues', 'Camera app crashes', 'Battery drain', 'Screen cracks'],
    averageRepairCost: 180,
  },
  {
    id: 'samsung-galaxy-s21-ultra',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S21 Ultra',
    year: 2021,
    imageUrl: '/images/devices/samsung-galaxy-s21-ultra.jpg',
    specifications: {
      screen: { size: '6.8"', resolution: '3200x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 888 / Exynos 2100',
      memory: '12GB - 16GB',
      storage: '128GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'S Pen support'],
      dimensions: { width: 165.1, height: 75.6, depth: 8.9, weight: 227 },
    },
    commonIssues: ['S Pen connectivity', 'Camera focus issues', 'Battery degradation', 'Green line display'],
    averageRepairCost: 160,
  },
  {
    id: 'samsung-galaxy-s20-ultra',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S20 Ultra',
    year: 2020,
    imageUrl: '/images/devices/samsung-galaxy-s20-ultra.jpg',
    specifications: {
      screen: { size: '6.9"', resolution: '3200x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 865 / Exynos 990',
      memory: '12GB - 16GB',
      storage: '128GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging'],
      dimensions: { width: 166.9, height: 76, depth: 8.8, weight: 220 },
    },
    commonIssues: ['Camera autofocus problems', 'Green tint display', 'Battery swelling', 'Charging issues'],
    averageRepairCost: 140,
  },
  {
    id: 'samsung-galaxy-note-20-ultra',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy Note 20 Ultra',
    year: 2020,
    imageUrl: '/images/devices/samsung-galaxy-note-20-ultra.jpg',
    specifications: {
      screen: { size: '6.9"', resolution: '3088x1440', type: 'Dynamic AMOLED 2X' },
      processor: 'Snapdragon 865+ / Exynos 990',
      memory: '12GB',
      storage: '128GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging', 'S Pen'],
      dimensions: { width: 164.8, height: 77.2, depth: 8.1, weight: 208 },
    },
    commonIssues: ['S Pen lag', 'Camera glass cracks', 'WiFi connectivity', 'Touch sensitivity'],
    averageRepairCost: 150,
  },
  {
    id: 'samsung-galaxy-s10-plus',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S10+',
    year: 2019,
    imageUrl: '/images/devices/samsung-galaxy-s10-plus.jpg',
    specifications: {
      screen: { size: '6.4"', resolution: '3040x1440', type: 'Dynamic AMOLED' },
      processor: 'Snapdragon 855 / Exynos 9820',
      memory: '8GB - 12GB',
      storage: '128GB - 1TB',
      ports: ['USB-C 3.1', 'Wireless charging', '3.5mm headphone'],
      dimensions: { width: 157.6, height: 74.1, depth: 7.8, weight: 175 },
    },
    commonIssues: ['Fingerprint sensor issues', 'Screen burn-in', 'Charging port wear', 'Camera glass scratches'],
    averageRepairCost: 120,
  },
  {
    id: 'samsung-galaxy-s9-plus',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S9+',
    year: 2018,
    imageUrl: '/images/devices/samsung-galaxy-s9-plus.jpg',
    specifications: {
      screen: { size: '6.2"', resolution: '2960x1440', type: 'Super AMOLED' },
      processor: 'Snapdragon 845 / Exynos 9810',
      memory: '6GB',
      storage: '64GB - 256GB',
      ports: ['USB-C 3.1', 'Wireless charging', '3.5mm headphone'],
      dimensions: { width: 158.1, height: 73.8, depth: 8.5, weight: 189 },
    },
    commonIssues: ['Purple/pink line display', 'Battery degradation', 'Charging port damage', 'Camera focus'],
    averageRepairCost: 100,
  },
  {
    id: 'samsung-galaxy-s8-plus',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S8+',
    year: 2017,
    imageUrl: '/images/devices/samsung-galaxy-s8-plus.jpg',
    specifications: {
      screen: { size: '6.2"', resolution: '2960x1440', type: 'Super AMOLED' },
      processor: 'Snapdragon 835 / Exynos 8895',
      memory: '4GB - 6GB',
      storage: '64GB - 128GB',
      ports: ['USB-C 3.1', 'Wireless charging', '3.5mm headphone'],
      dimensions: { width: 159.5, height: 73.4, depth: 8.1, weight: 173 },
    },
    commonIssues: ['Screen burn-in', 'Battery swelling', 'Charging port issues', 'Red tint display'],
    averageRepairCost: 90,
  },
  {
    id: 'samsung-galaxy-s7-edge',
    categoryId: 'android-phone',
    brand: 'Samsung',
    name: 'Galaxy S7 Edge',
    year: 2016,
    imageUrl: '/images/devices/samsung-galaxy-s7-edge.jpg',
    specifications: {
      screen: { size: '5.5"', resolution: '2560x1440', type: 'Super AMOLED' },
      processor: 'Snapdragon 820 / Exynos 8890',
      memory: '4GB',
      storage: '32GB - 128GB',
      ports: ['USB-C 2.0', 'Wireless charging', '3.5mm headphone'],
      dimensions: { width: 150.9, height: 72.6, depth: 7.7, weight: 157 },
    },
    commonIssues: ['Pink line display', 'Edge touch issues', 'Water damage', 'Battery degradation'],
    averageRepairCost: 80,
  },
];

// Older Google Pixel models (2016-2021)
export const pixelLegacyModels: DeviceModel[] = [
  {
    id: 'google-pixel-7-pro',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 7 Pro',
    year: 2022,
    imageUrl: '/images/devices/google-pixel-7-pro.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '3120x1440', type: 'LTPO OLED' },
      processor: 'Google Tensor G2',
      memory: '12GB',
      storage: '128GB - 512GB',
      ports: ['USB-C 3.2', 'Wireless charging'],
      dimensions: { width: 162.9, height: 76.6, depth: 8.9, weight: 210 },
    },
    commonIssues: ['Camera bar scratches', 'Fingerprint sensor slow', 'Signal reception', 'Battery optimization'],
    averageRepairCost: 150,
  },
  {
    id: 'google-pixel-6-pro',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 6 Pro',
    year: 2021,
    imageUrl: '/images/devices/google-pixel-6-pro.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '3120x1440', type: 'LTPO OLED' },
      processor: 'Google Tensor',
      memory: '12GB',
      storage: '128GB - 512GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 163.9, height: 75.9, depth: 8.9, weight: 210 },
    },
    commonIssues: ['Camera bar damage', 'Connectivity issues', 'Overheating', 'Slow charging'],
    averageRepairCost: 140,
  },
  {
    id: 'google-pixel-5',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 5',
    year: 2020,
    imageUrl: '/images/devices/google-pixel-5.jpg',
    specifications: {
      screen: { size: '6.0"', resolution: '2340x1080', type: 'OLED' },
      processor: 'Snapdragon 765G',
      memory: '8GB',
      storage: '128GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 144.7, height: 70.4, depth: 8, weight: 151 },
    },
    commonIssues: ['Screen gap issues', 'Speaker problems', 'Charging port wear', 'Battery drain'],
    averageRepairCost: 120,
  },
  {
    id: 'google-pixel-4-xl',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 4 XL',
    year: 2019,
    imageUrl: '/images/devices/google-pixel-4-xl.jpg',
    specifications: {
      screen: { size: '6.3"', resolution: '3040x1440', type: 'OLED 90Hz' },
      processor: 'Snapdragon 855',
      memory: '6GB',
      storage: '64GB - 128GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 160.4, height: 75.1, depth: 8.2, weight: 193 },
    },
    commonIssues: ['Face unlock issues', 'Battery degradation', 'Screen uniformity', 'Radar sensor problems'],
    averageRepairCost: 110,
  },
  {
    id: 'google-pixel-3-xl',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 3 XL',
    year: 2018,
    imageUrl: '/images/devices/google-pixel-3-xl.jpg',
    specifications: {
      screen: { size: '6.3"', resolution: '2960x1440', type: 'OLED' },
      processor: 'Snapdragon 845',
      memory: '4GB',
      storage: '64GB - 128GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 158, height: 76.7, depth: 7.9, weight: 184 },
    },
    commonIssues: ['Pink tint display', 'Memory management', 'Charging issues', 'Camera app crashes'],
    averageRepairCost: 100,
  },
  {
    id: 'google-pixel-2-xl',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel 2 XL',
    year: 2017,
    imageUrl: '/images/devices/google-pixel-2-xl.jpg',
    specifications: {
      screen: { size: '6.0"', resolution: '2880x1440', type: 'OLED' },
      processor: 'Snapdragon 835',
      memory: '4GB',
      storage: '64GB - 128GB',
      ports: ['USB-C 3.1'],
      dimensions: { width: 157.9, height: 76.7, depth: 7.9, weight: 175 },
    },
    commonIssues: ['Blue tint display', 'Screen burn-in', 'Audio distortion', 'Bootloop issues'],
    averageRepairCost: 90,
  },
  {
    id: 'google-pixel-xl',
    categoryId: 'android-phone',
    brand: 'Google',
    name: 'Pixel XL',
    year: 2016,
    imageUrl: '/images/devices/google-pixel-xl.jpg',
    specifications: {
      screen: { size: '5.5"', resolution: '2560x1440', type: 'AMOLED' },
      processor: 'Snapdragon 821',
      memory: '4GB',
      storage: '32GB - 128GB',
      ports: ['USB-C 3.0', '3.5mm headphone adapter'],
      dimensions: { width: 154.7, height: 75.7, depth: 8.6, weight: 168 },
    },
    commonIssues: ['Microphone failure', 'GPS issues', 'Battery degradation', 'Charging problems'],
    averageRepairCost: 80,
  },
];

// OnePlus legacy models (2016-2021)
export const oneplusLegacyModels: DeviceModel[] = [
  {
    id: 'oneplus-10-pro',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 10 Pro',
    year: 2022,
    imageUrl: '/images/devices/oneplus-10-pro.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '3216x1440', type: 'LTPO AMOLED' },
      processor: 'Snapdragon 8 Gen 1',
      memory: '8GB - 12GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 163, height: 73.9, depth: 8.55, weight: 200.5 },
    },
    commonIssues: ['Camera Hasselblad issues', 'Green line display', 'Charging speed problems', 'Alert slider'],
    averageRepairCost: 130,
  },
  {
    id: 'oneplus-9-pro',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 9 Pro',
    year: 2021,
    imageUrl: '/images/devices/oneplus-9-pro.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '3216x1440', type: 'LTPO AMOLED' },
      processor: 'Snapdragon 888',
      memory: '8GB - 12GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 163.2, height: 73.6, depth: 8.7, weight: 197 },
    },
    commonIssues: ['Overheating', 'Camera color calibration', 'Display tint', 'Battery optimization'],
    averageRepairCost: 120,
  },
  {
    id: 'oneplus-8-pro',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 8 Pro',
    year: 2020,
    imageUrl: '/images/devices/oneplus-8-pro.jpg',
    specifications: {
      screen: { size: '6.78"', resolution: '3168x1440', type: 'AMOLED 120Hz' },
      processor: 'Snapdragon 865',
      memory: '8GB - 12GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 3.1', 'Wireless charging'],
      dimensions: { width: 165.3, height: 74.35, depth: 8.99, weight: 199 },
    },
    commonIssues: ['Green tint display', 'Camera filter X-ray issue', 'Wireless charging problems', 'Black crush'],
    averageRepairCost: 110,
  },
  {
    id: 'oneplus-7t-pro',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 7T Pro',
    year: 2019,
    imageUrl: '/images/devices/oneplus-7t-pro.jpg',
    specifications: {
      screen: { size: '6.67"', resolution: '3120x1440', type: 'AMOLED 90Hz' },
      processor: 'Snapdragon 855+',
      memory: '8GB - 12GB',
      storage: '256GB',
      ports: ['USB-C 3.1', 'Pop-up selfie camera'],
      dimensions: { width: 162.6, height: 75.9, depth: 8.8, weight: 206 },
    },
    commonIssues: ['Pop-up camera mechanism', 'Alert slider problems', 'Display burn-in', 'Charging port wear'],
    averageRepairCost: 100,
  },
  {
    id: 'oneplus-6t',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 6T',
    year: 2018,
    imageUrl: '/images/devices/oneplus-6t.jpg',
    specifications: {
      screen: { size: '6.41"', resolution: '2340x1080', type: 'AMOLED' },
      processor: 'Snapdragon 845',
      memory: '6GB - 8GB',
      storage: '128GB - 256GB',
      ports: ['USB-C 2.0'],
      dimensions: { width: 157.5, height: 74.8, depth: 8.2, weight: 185 },
    },
    commonIssues: ['In-display fingerprint issues', 'Black crush', 'Charging problems', 'Ghost touch'],
    averageRepairCost: 90,
  },
  {
    id: 'oneplus-5t',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 5T',
    year: 2017,
    imageUrl: '/images/devices/oneplus-5t.jpg',
    specifications: {
      screen: { size: '6.01"', resolution: '2160x1080', type: 'AMOLED' },
      processor: 'Snapdragon 835',
      memory: '6GB - 8GB',
      storage: '64GB - 128GB',
      ports: ['USB-C 2.0', '3.5mm headphone'],
      dimensions: { width: 156.1, height: 75, depth: 7.25, weight: 162 },
    },
    commonIssues: ['Jelly scrolling', 'Fingerprint sensor lag', 'Camera focusing', 'WiFi connectivity'],
    averageRepairCost: 80,
  },
  {
    id: 'oneplus-3t',
    categoryId: 'android-phone',
    brand: 'OnePlus',
    name: 'OnePlus 3T',
    year: 2016,
    imageUrl: '/images/devices/oneplus-3t.jpg',
    specifications: {
      screen: { size: '5.5"', resolution: '1920x1080', type: 'AMOLED' },
      processor: 'Snapdragon 821',
      memory: '6GB',
      storage: '64GB - 128GB',
      ports: ['USB-C 2.0', '3.5mm headphone'],
      dimensions: { width: 152.7, height: 74.7, depth: 7.35, weight: 158 },
    },
    commonIssues: ['Button wear', 'Charging port damage', 'Screen burn-in', 'GPS accuracy'],
    averageRepairCost: 70,
  },
];

// Combine all Android devices
export const allAndroidDevices: DeviceModel[] = [
  ...samsungModels,
  ...samsungLegacyModels,
  ...pixelModels,
  ...pixelLegacyModels,
  ...oneplusModels,
  ...oneplusLegacyModels,
  ...xiaomiModels,
];

export default {
  categories: androidCategories,
  devices: allAndroidDevices,
  samsung: [...samsungModels, ...samsungLegacyModels],
  pixel: [...pixelModels, ...pixelLegacyModels],
  oneplus: [...oneplusModels, ...oneplusLegacyModels],
  xiaomi: xiaomiModels,
  legacy: {
    samsung: samsungLegacyModels,
    pixel: pixelLegacyModels,
    oneplus: oneplusLegacyModels,
  },
};