import { DeviceCategory, DeviceModel } from '@/lib/services/types';

// Apple device categories
export const appleCategories: DeviceCategory[] = [
  {
    id: 'macbook',
    name: 'MacBook',
    description: 'Apple MacBook laptops - Air and Pro models',
    icon: 'laptop',
    brands: ['Apple'],
    popularModels: ['MacBook Air M3', 'MacBook Pro 14" M4', 'MacBook Pro 16" M4'],
  },
  {
    id: 'imac',
    name: 'iMac',
    description: 'Apple iMac all-in-one desktop computers',
    icon: 'desktop',
    brands: ['Apple'],
    popularModels: ['iMac 24" M4', 'iMac 24" M3'],
  },
  {
    id: 'mac-mini',
    name: 'Mac Mini',
    description: 'Apple Mac Mini compact desktop computers',
    icon: 'cpu',
    brands: ['Apple'],
    popularModels: ['Mac Mini M4', 'Mac Mini M2'],
  },
  {
    id: 'mac-studio',
    name: 'Mac Studio',
    description: 'Apple Mac Studio high-performance compact desktops',
    icon: 'cpu',
    brands: ['Apple'],
    popularModels: ['Mac Studio M2 Ultra', 'Mac Studio M2 Max'],
  },
  {
    id: 'mac-pro',
    name: 'Mac Pro',
    description: 'Apple Mac Pro professional workstations',
    icon: 'cpu',
    brands: ['Apple'],
    popularModels: ['Mac Pro M2 Ultra', 'Mac Pro Intel'],
  },
  {
    id: 'iphone',
    name: 'iPhone',
    description: 'Apple iPhone smartphones',
    icon: 'smartphone',
    brands: ['Apple'],
    popularModels: ['iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16 Plus', 'iPhone 16', 'iPhone 15 Pro Max', 'iPhone 15 Pro'],
  },
  {
    id: 'ipad',
    name: 'iPad',
    description: 'Apple iPad tablets',
    icon: 'tablet',
    brands: ['Apple'],
    popularModels: ['iPad Pro 13" M4', 'iPad Pro 11" M4', 'iPad Air 13" M2', 'iPad Air 11" M2'],
  },
];

// MacBook models (2016-2025)
export const macbookModels: DeviceModel[] = [
  // MacBook Pro M4 (2024)
  {
    id: 'macbook-pro-14-m4-2024',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 14" M4',
    year: 2024,
    imageUrl: '/images/devices/macbook-pro-14-m4-2024.jpg',
    specifications: {
      screen: { size: '14.2"', resolution: '3024x1964', type: 'Liquid Retina XDR' },
      processor: 'Apple M4, M4 Pro, or M4 Max (up to 14-core CPU, 32-core GPU)',
      memory: '16GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 5/4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 312.6, height: 221.2, depth: 15.5, weight: 1.55 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen flickering', 'Thermal management', 'Port connectivity', 'Battery optimization'],
    averageRepairCost: 450,
  },
  {
    id: 'macbook-pro-16-m4-2024',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 16" M4',
    year: 2024,
    imageUrl: '/images/devices/macbook-pro-16-m4-2024.jpg',
    specifications: {
      screen: { size: '16.2"', resolution: '3456x2234', type: 'Liquid Retina XDR' },
      processor: 'Apple M4 Pro or M4 Max (up to 14-core CPU, 32-core GPU)',
      memory: '24GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 5/4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 355.7, height: 248.1, depth: 16.8, weight: 2.14 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen flickering', 'Thermal management', 'Port connectivity', 'Battery optimization'],
    averageRepairCost: 520,
  },

  // MacBook Air M3 (2024)
  {
    id: 'macbook-air-13-m3-2024',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Air 13" M3',
    year: 2024,
    imageUrl: '/images/devices/macbook-air-13-m3-2024.jpg',
    specifications: {
      screen: { size: '13.6"', resolution: '2560x1664', type: 'Liquid Retina' },
      processor: 'Apple M3 (8-core CPU, 8/10-core GPU)',
      memory: '8GB - 24GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 304.1, height: 215, depth: 11.3, weight: 1.24 },
    },
    commonIssues: ['Battery drain', 'Keyboard issues', 'Screen flickering', 'Overheating'],
    averageRepairCost: 280,
  },
  {
    id: 'macbook-air-15-m3-2024',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Air 15" M3',
    year: 2024,
    imageUrl: '/images/devices/macbook-air-15-m3-2024.jpg',
    specifications: {
      screen: { size: '15.3"', resolution: '2880x1864', type: 'Liquid Retina' },
      processor: 'Apple M3 (8-core CPU, 10-core GPU)',
      memory: '8GB - 24GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 340.4, height: 237.6, depth: 11.5, weight: 1.51 },
    },
    commonIssues: ['Battery drain', 'Keyboard issues', 'Screen flickering', 'Overheating'],
    averageRepairCost: 320,
  },

  // MacBook Pro M3 (2023)
  {
    id: 'macbook-pro-14-m3-2023',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 14" M3',
    year: 2023,
    imageUrl: '/images/devices/macbook-pro-14-m3-2023.jpg',
    specifications: {
      screen: { size: '14.2"', resolution: '3024x1964', type: 'Liquid Retina XDR' },
      processor: 'Apple M3, M3 Pro, or M3 Max',
      memory: '8GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 312.6, height: 221.2, depth: 15.5, weight: 1.55 },
    },
    commonIssues: ['Screen flickering', 'Keyboard issues', 'Battery drain', 'Port problems'],
    averageRepairCost: 420,
  },
  {
    id: 'macbook-pro-16-m3-2023',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 16" M3',
    year: 2023,
    imageUrl: '/images/devices/macbook-pro-16-m3-2023.jpg',
    specifications: {
      screen: { size: '16.2"', resolution: '3456x2234', type: 'Liquid Retina XDR' },
      processor: 'Apple M3 Pro or M3 Max',
      memory: '18GB - 128GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['3x Thunderbolt 4', 'HDMI', 'SDXC', 'MagSafe 3', '3.5mm headphone'],
      dimensions: { width: 355.7, height: 248.1, depth: 16.8, weight: 2.15 },
    },
    commonIssues: ['Screen flickering', 'Keyboard issues', 'Battery drain', 'Port problems'],
    averageRepairCost: 480,
  },

  // MacBook Pro M2 (2022)
  {
    id: 'macbook-pro-13-m2-2022',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 13" M2',
    year: 2022,
    imageUrl: '/images/devices/macbook-pro-13-m2-2022.jpg',
    specifications: {
      screen: { size: '13.3"', resolution: '2560x1600', type: 'Retina' },
      processor: 'Apple M2 (8-core CPU, 10-core GPU)',
      memory: '8GB - 24GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', '3.5mm headphone'],
      dimensions: { width: 304.1, height: 212.4, depth: 15.6, weight: 1.4 },
    },
    commonIssues: ['Touch Bar issues', 'Keyboard problems', 'Battery drain', 'Overheating'],
    averageRepairCost: 350,
  },

  // MacBook Air M1 (2020)
  {
    id: 'macbook-air-13-m1-2020',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Air 13" M1',
    year: 2020,
    imageUrl: '/images/devices/macbook-air-13-m1-2020.jpg',
    specifications: {
      screen: { size: '13.3"', resolution: '2560x1600', type: 'Retina' },
      processor: 'Apple M1 (8-core CPU, 7/8-core GPU)',
      memory: '8GB - 16GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', '3.5mm headphone'],
      dimensions: { width: 304.1, height: 212.4, depth: 4.1, weight: 1.29 },
    },
    commonIssues: ['Screen coating wear', 'Keyboard issues', 'Battery drain', 'Port problems'],
    averageRepairCost: 280,
  },

  // Intel MacBooks (2016-2019)
  {
    id: 'macbook-pro-16-intel-2019',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 16" Intel',
    year: 2019,
    imageUrl: '/images/devices/macbook-pro-16-intel-2019.jpg',
    specifications: {
      screen: { size: '16"', resolution: '3072x1920', type: 'Retina' },
      processor: 'Intel Core i7/i9 (6/8-core)',
      memory: '16GB - 64GB DDR4',
      storage: '512GB - 8TB SSD',
      graphics: 'AMD Radeon Pro 5300M/5500M/5600M',
      ports: ['4x Thunderbolt 3', '3.5mm headphone'],
      dimensions: { width: 357.9, height: 245.9, depth: 16.2, weight: 2.0 },
    },
    commonIssues: ['Keyboard butterfly mechanism', 'Flexgate display issues', 'Thermal throttling', 'Battery swelling'],
    averageRepairCost: 450,
  },
  {
    id: 'macbook-pro-13-intel-2016',
    categoryId: 'macbook',
    brand: 'Apple',
    name: 'MacBook Pro 13" Intel Touch Bar',
    year: 2016,
    imageUrl: '/images/devices/macbook-pro-13-intel-2016.jpg',
    specifications: {
      screen: { size: '13.3"', resolution: '2560x1600', type: 'Retina' },
      processor: 'Intel Core i5/i7 (dual-core)',
      memory: '8GB - 16GB LPDDR3',
      storage: '256GB - 2TB SSD',
      graphics: 'Intel Iris Graphics 550',
      ports: ['4x Thunderbolt 3', '3.5mm headphone'],
      dimensions: { width: 304.1, height: 212.4, depth: 14.9, weight: 1.37 },
    },
    commonIssues: ['Butterfly keyboard', 'Touch Bar failure', 'Flexgate', 'Battery swelling', 'Logic board failure'],
    averageRepairCost: 380,
  },
];

// iPhone models (2016-2025)
export const iphoneModels: DeviceModel[] = [
  // iPhone 16 Series (2024)
  {
    id: 'iphone-16-pro-max',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 16 Pro Max',
    year: 2024,
    imageUrl: '/images/devices/iphone-16-pro-max.jpg',
    specifications: {
      screen: { size: '6.9"', resolution: '2868x1320', type: 'Super Retina XDR OLED ProMotion' },
      processor: 'A18 Pro',
      memory: '8GB',
      storage: '256GB - 1TB',
      cameras: 'Triple camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto 5x)',
      connectivity: 'USB-C, 5G, Wi-Fi 7, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Camera Control button problems'],
    averageRepairCost: 280,
  },
  {
    id: 'iphone-16-pro',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 16 Pro',
    year: 2024,
    imageUrl: '/images/devices/iphone-16-pro.jpg',
    specifications: {
      screen: { size: '6.3"', resolution: '2622x1206', type: 'Super Retina XDR OLED ProMotion' },
      processor: 'A18 Pro',
      memory: '8GB',
      storage: '128GB - 1TB',
      cameras: 'Triple camera system (48MP Main, 48MP Ultra Wide, 12MP Telephoto 5x)',
      connectivity: 'USB-C, 5G, Wi-Fi 7, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Camera Control button problems'],
    averageRepairCost: 260,
  },
  {
    id: 'iphone-16-plus',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 16 Plus',
    year: 2024,
    imageUrl: '/images/devices/iphone-16-plus.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A18',
      memory: '8GB',
      storage: '128GB - 512GB',
      cameras: 'Dual camera system (48MP Main, 12MP Ultra Wide)',
      connectivity: 'USB-C, 5G, Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Action button problems'],
    averageRepairCost: 220,
  },
  {
    id: 'iphone-16',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 16',
    year: 2024,
    imageUrl: '/images/devices/iphone-16.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A18',
      memory: '8GB',
      storage: '128GB - 512GB',
      cameras: 'Dual camera system (48MP Main, 12MP Ultra Wide)',
      connectivity: 'USB-C, 5G, Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Screen cracks', 'Camera lens damage', 'Battery degradation', 'USB-C port issues', 'Action button problems'],
    averageRepairCost: 200,
  },

  // iPhone 15 Series (2023)
  {
    id: 'iphone-15-pro-max',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 15 Pro Max',
    year: 2023,
    imageUrl: '/images/devices/iphone-15-pro-max.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A17 Pro',
      memory: '8GB',
      storage: '256GB - 1TB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 220,
  },
  {
    id: 'iphone-15-pro',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 15 Pro',
    year: 2023,
    imageUrl: '/images/devices/iphone-15-pro.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A17 Pro',
      memory: '8GB',
      storage: '128GB - 1TB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 200,
  },
  {
    id: 'iphone-15-plus',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 15 Plus',
    year: 2023,
    imageUrl: '/images/devices/iphone-15-plus.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A16 Bionic',
      memory: '6GB',
      storage: '128GB - 512GB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 180,
  },
  {
    id: 'iphone-15',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 15',
    year: 2023,
    imageUrl: '/images/devices/iphone-15.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A16 Bionic',
      memory: '6GB',
      storage: '128GB - 512GB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Charging port problems'],
    averageRepairCost: 160,
  },

  // iPhone 14 Series (2022)
  {
    id: 'iphone-14-pro-max',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 14 Pro Max',
    year: 2022,
    imageUrl: '/images/devices/iphone-14-pro-max.jpg',
    specifications: {
      screen: { size: '6.7"', resolution: '2796x1290', type: 'Super Retina XDR OLED' },
      processor: 'A16 Bionic',
      memory: '6GB',
      storage: '128GB - 1TB',
    },
    commonIssues: ['Dynamic Island issues', 'Screen cracks', 'Battery degradation', 'Camera problems'],
    averageRepairCost: 200,
  },
  {
    id: 'iphone-14-pro',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 14 Pro',
    year: 2022,
    imageUrl: '/images/devices/iphone-14-pro.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2556x1179', type: 'Super Retina XDR OLED' },
      processor: 'A16 Bionic',
      memory: '6GB',
      storage: '128GB - 1TB',
    },
    commonIssues: ['Dynamic Island issues', 'Screen cracks', 'Battery degradation', 'Camera problems'],
    averageRepairCost: 180,
  },

  // Older iPhone models
  {
    id: 'iphone-13-pro',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 13 Pro',
    year: 2021,
    imageUrl: '/images/devices/iphone-13-pro.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2532x1170', type: 'Super Retina XDR OLED' },
      processor: 'A15 Bionic',
      memory: '6GB',
      storage: '128GB - 1TB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Camera issues', 'Face ID problems'],
    averageRepairCost: 160,
  },
  {
    id: 'iphone-12',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone 12',
    year: 2020,
    imageUrl: '/images/devices/iphone-12.jpg',
    specifications: {
      screen: { size: '6.1"', resolution: '2532x1170', type: 'Super Retina XDR OLED' },
      processor: 'A14 Bionic',
      memory: '4GB',
      storage: '64GB - 256GB',
    },
    commonIssues: ['Screen cracks', 'Battery degradation', 'Charging issues', 'Speaker problems'],
    averageRepairCost: 140,
  },
  {
    id: 'iphone-se-3rd-gen',
    categoryId: 'iphone',
    brand: 'Apple',
    name: 'iPhone SE (3rd generation)',
    year: 2022,
    imageUrl: '/images/devices/iphone-se-3rd-gen.jpg',
    specifications: {
      screen: { size: '4.7"', resolution: '1334x750', type: 'Retina HD LCD' },
      processor: 'A15 Bionic',
      memory: '4GB',
      storage: '64GB - 256GB',
    },
    commonIssues: ['Home button issues', 'Screen cracks', 'Battery degradation', 'Charging problems'],
    averageRepairCost: 120,
  },
];

// iMac models (2016-2025)
export const imacModels: DeviceModel[] = [
  {
    id: 'imac-24-m4-2024',
    categoryId: 'imac',
    brand: 'Apple',
    name: 'iMac 24" M4',
    year: 2024,
    imageUrl: '/images/devices/imac-24-m4-2024.jpg',
    specifications: {
      screen: { size: '24"', resolution: '4480x2520', type: '4.5K Retina' },
      processor: 'Apple M4 (8/10-core CPU, 8/10-core GPU)',
      memory: '16GB - 32GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['4x Thunderbolt 4', '2x USB 3', 'Gigabit Ethernet (optional)', '3.5mm headphone'],
      dimensions: { width: 547, height: 461.2, depth: 147, weight: 4.43 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Display uniformity', 'Thermal management', 'Port connectivity', 'Stand adjustment'],
    averageRepairCost: 420,
  },
  {
    id: 'imac-24-m3-2023',
    categoryId: 'imac',
    brand: 'Apple',
    name: 'iMac 24" M3',
    year: 2023,
    imageUrl: '/images/devices/imac-24-m3-2023.jpg',
    specifications: {
      screen: { size: '24"', resolution: '4480x2520', type: '4.5K Retina' },
      processor: 'Apple M3 (8-core CPU, 8/10-core GPU)',
      memory: '8GB - 24GB unified memory',
      storage: '256GB - 2TB SSD',
      ports: ['2x Thunderbolt/USB 4', '2x USB 3', 'Gigabit Ethernet', '3.5mm headphone'],
      dimensions: { width: 547, height: 461.2, depth: 147, weight: 4.46 },
    },
    commonIssues: ['Display backlight bleeding', 'Power supply issues', 'Fan noise', 'Logic board problems'],
    averageRepairCost: 380,
  },
  {
    id: 'imac-27-intel-2020',
    categoryId: 'imac',
    brand: 'Apple',
    name: 'iMac 27" Intel',
    year: 2020,
    imageUrl: '/images/devices/imac-27-intel-2020.jpg',
    specifications: {
      screen: { size: '27"', resolution: '5120x2880', type: '5K Retina' },
      processor: 'Intel Core i5/i7/i9 (6/8/10-core)',
      memory: '8GB - 128GB DDR4',
      storage: '256GB SSD - 8TB Fusion Drive',
      graphics: 'AMD Radeon Pro 5300/5500 XT/5700/5700 XT',
      ports: ['2x Thunderbolt 3', '4x USB 3', 'Gigabit Ethernet', 'SDXC', '3.5mm headphone'],
      dimensions: { width: 650.8, height: 516.3, depth: 203, weight: 9.44 },
    },
    commonIssues: ['Fusion Drive failure', 'Graphics card issues', 'Power supply problems', 'Display issues'],
    averageRepairCost: 420,
  },
];

// Mac Mini models
export const macMiniModels: DeviceModel[] = [
  {
    id: 'mac-mini-m4-2024',
    categoryId: 'mac-mini',
    brand: 'Apple',
    name: 'Mac Mini M4',
    year: 2024,
    imageUrl: '/images/devices/mac-mini-m4-2024.jpg',
    specifications: {
      processor: 'Apple M4 or M4 Pro (10/12-core CPU, 10/16-core GPU)',
      memory: '16GB - 64GB unified memory',
      storage: '256GB - 8TB SSD',
      ports: ['5x USB-C (Thunderbolt 4)', 'HDMI', 'Gigabit Ethernet', '3.5mm headphone'],
      dimensions: { width: 197, height: 197, depth: 35, weight: 0.67 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Port connectivity', 'Thermal management', 'Power supply issues', 'External display issues'],
    averageRepairCost: 280,
  },
  {
    id: 'mac-mini-m2-2023',
    categoryId: 'mac-mini',
    brand: 'Apple',
    name: 'Mac Mini M2',
    year: 2023,
    imageUrl: '/images/devices/mac-mini-m2-2023.jpg',
    specifications: {
      processor: 'Apple M2 or M2 Pro (8/12-core CPU, 10/19-core GPU)',
      memory: '8GB - 32GB unified memory',
      storage: '256GB - 8TB SSD',
      ports: ['4x Thunderbolt 4', '2x USB-A', 'HDMI', 'Gigabit Ethernet', '3.5mm headphone'],
      dimensions: { width: 197, height: 197, depth: 35, weight: 1.18 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Port connectivity', 'Thermal management', 'Power supply issues', 'External display issues'],
    averageRepairCost: 250,
  },
];

// Mac Studio models
export const macStudioModels: DeviceModel[] = [
  {
    id: 'mac-studio-m2-ultra-2023',
    categoryId: 'mac-studio',
    brand: 'Apple',
    name: 'Mac Studio M2 Ultra',
    year: 2023,
    imageUrl: '/images/devices/mac-studio-m2-ultra-2023.jpg',
    specifications: {
      processor: 'Apple M2 Ultra (24-core CPU, 60/76-core GPU)',
      memory: '64GB - 192GB unified memory',
      storage: '1TB - 8TB SSD',
      ports: ['6x Thunderbolt 4', '2x USB-A', 'HDMI', '10Gb Ethernet', '3.5mm headphone'],
      dimensions: { width: 197, height: 197, depth: 95, weight: 2.7 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Thermal management', 'Port connectivity', 'Power supply issues', 'Fan noise'],
    averageRepairCost: 650,
  },
  {
    id: 'mac-studio-m2-max-2023',
    categoryId: 'mac-studio',
    brand: 'Apple',
    name: 'Mac Studio M2 Max',
    year: 2023,
    imageUrl: '/images/devices/mac-studio-m2-max-2023.jpg',
    specifications: {
      processor: 'Apple M2 Max (12-core CPU, 30/38-core GPU)',
      memory: '32GB - 96GB unified memory',
      storage: '512GB - 8TB SSD',
      ports: ['6x Thunderbolt 4', '2x USB-A', 'HDMI', '10Gb Ethernet', '3.5mm headphone'],
      dimensions: { width: 197, height: 197, depth: 95, weight: 2.7 },
      connectivity: 'Wi-Fi 6E, Bluetooth 5.3',
    },
    commonIssues: ['Thermal management', 'Port connectivity', 'Power supply issues', 'Fan noise'],
    averageRepairCost: 550,
  },
];

// iPad models
export const ipadModels: DeviceModel[] = [
  {
    id: 'ipad-pro-13-m4-2024',
    categoryId: 'ipad',
    brand: 'Apple',
    name: 'iPad Pro 13" M4',
    year: 2024,
    imageUrl: '/images/devices/ipad-pro-13-m4-2024.jpg',
    specifications: {
      screen: { size: '13"', resolution: '2752x2064', type: 'Ultra Retina XDR OLED' },
      processor: 'Apple M4 (9/10-core CPU, 10-core GPU)',
      memory: '8GB - 16GB',
      storage: '256GB - 2TB',
      connectivity: 'USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
      cameras: '12MP Wide, 10MP Ultra Wide, LiDAR Scanner',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil Pro connectivity', 'USB-C port issues', 'OLED burn-in', 'Bent frame'],
    averageRepairCost: 350,
  },
  {
    id: 'ipad-pro-11-m4-2024',
    categoryId: 'ipad',
    brand: 'Apple',
    name: 'iPad Pro 11" M4',
    year: 2024,
    imageUrl: '/images/devices/ipad-pro-11-m4-2024.jpg',
    specifications: {
      screen: { size: '11"', resolution: '2420x1668', type: 'Ultra Retina XDR OLED' },
      processor: 'Apple M4 (9/10-core CPU, 10-core GPU)',
      memory: '8GB - 16GB',
      storage: '256GB - 2TB',
      connectivity: 'USB-C (Thunderbolt/USB 4), Wi-Fi 6E, Bluetooth 5.3',
      cameras: '12MP Wide, 10MP Ultra Wide, LiDAR Scanner',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil Pro connectivity', 'USB-C port issues', 'OLED burn-in', 'Bent frame'],
    averageRepairCost: 320,
  },
  {
    id: 'ipad-air-13-m2-2024',
    categoryId: 'ipad',
    brand: 'Apple',
    name: 'iPad Air 13" M2',
    year: 2024,
    imageUrl: '/images/devices/ipad-air-13-m2-2024.jpg',
    specifications: {
      screen: { size: '13"', resolution: '2732x2048', type: 'Liquid Retina' },
      processor: 'Apple M2 (8-core CPU, 10-core GPU)',
      memory: '8GB',
      storage: '128GB - 1TB',
      connectivity: 'USB-C, Wi-Fi 6E, Bluetooth 5.3',
      cameras: '12MP Wide, 12MP Ultra Wide',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil connectivity', 'USB-C port issues', 'Touch ID problems', 'Speaker issues'],
    averageRepairCost: 280,
  },
  {
    id: 'ipad-air-11-m2-2024',
    categoryId: 'ipad',
    brand: 'Apple',
    name: 'iPad Air 11" M2',
    year: 2024,
    imageUrl: '/images/devices/ipad-air-11-m2-2024.jpg',
    specifications: {
      screen: { size: '11"', resolution: '2360x1640', type: 'Liquid Retina' },
      processor: 'Apple M2 (8-core CPU, 10-core GPU)',
      memory: '8GB',
      storage: '128GB - 1TB',
      connectivity: 'USB-C, Wi-Fi 6E, Bluetooth 5.3',
      cameras: '12MP Wide, 12MP Ultra Wide',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil connectivity', 'USB-C port issues', 'Touch ID problems', 'Speaker issues'],
    averageRepairCost: 250,
  },
  {
    id: 'ipad-pro-12-9-m2-2022',
    categoryId: 'ipad',
    brand: 'Apple',
    name: 'iPad Pro 12.9" M2',
    year: 2022,
    imageUrl: '/images/devices/ipad-pro-12-9-m2-2022.jpg',
    specifications: {
      screen: { size: '12.9"', resolution: '2732x2048', type: 'Liquid Retina XDR' },
      processor: 'Apple M2 (8-core CPU, 10-core GPU)',
      memory: '8GB - 16GB',
      storage: '128GB - 2TB',
    },
    commonIssues: ['Screen cracks', 'Apple Pencil connectivity', 'Charging port issues', 'Bent frame'],
    averageRepairCost: 280,
  },
  {
    id: 'ipad-air-5th-gen',
    categoryId: 'ipad',
    brand: 'Apple',
    name: 'iPad Air (5th generation)',
    year: 2022,
    imageUrl: '/images/devices/ipad-air-5th-gen.jpg',
    specifications: {
      screen: { size: '10.9"', resolution: '2360x1640', type: 'Liquid Retina' },
      processor: 'Apple M1 (8-core CPU, 8-core GPU)',
      memory: '8GB',
      storage: '64GB - 256GB',
    },
    commonIssues: ['Screen cracks', 'Touch ID issues', 'Charging problems', 'Speaker issues'],
    averageRepairCost: 220,
  },
];

// Combine all Apple devices
export const allAppleDevices: DeviceModel[] = [
  ...macbookModels,
  ...iphoneModels,
  ...imacModels,
  ...macMiniModels,
  ...macStudioModels,
  ...ipadModels,
];

export default {
  categories: appleCategories,
  devices: allAppleDevices,
  macbooks: macbookModels,
  iphones: iphoneModels,
  imacs: imacModels,
  macMinis: macMiniModels,
  macStudios: macStudioModels,
  ipads: ipadModels,
};